version: '2'
services:
  review:
    image: floodplain/demo-mongodb-review
    environment:
      MONGODB_CONNECTION_STRING: mongodb://mongo:27017
    depends_on:
      - mongo
  mongo:
    image: mongo:4.0
    ports:
      - "27017:27017"
